// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Report_and_Analytics_API.Data;

#nullable disable

namespace Report_and_Analytics_API.Migrations
{
    [DbContext(typeof(HistoricalReportDbContext))]
    [Migration("20250827034529_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIResponses.Hostorical_Report_Models.employeePayrollStatementReportFinalData", b =>
                {
                    b.Property<int?>("reportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("reportId"));

                    b.Property<decimal?>("GrossPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("dateGenerated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("employeeId")
                        .HasColumnType("int");

                    b.Property<string>("employeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("overtimePay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("payCycleAbsenceDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("payCycleGrossPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("payCycleLoanDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("payCycleNetpay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("payCyclePhilHealthDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("payCycleSssDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("payCycleTotalDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("payPeriodStartDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ytdAbsenceDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ytdLoanDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ytdNetPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ytdTotalDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ytdphilHealthDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ytdsssDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("reportId");

                    b.ToTable("payrollInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
